### PR TITLE
fix scrollbars on bloomberg after removing tracking begging overlay

### PR DESCRIPTION
**Pull request by sandsmark**

### CODE REVIEW

**Comment by NicolaeNMV** [comment]
@sandsmark thanks for your PR !

By the way, on which page have you tested this ? Is it mobile/desktop ? On Chrome? I've quickly checked the Bloomberg website and the current extension seem to be working fine.

**Comment by sandsmark** [comment]
I don't remember the article, but I've noticed a similar issue on other sides (which I didn't debug, but I assume it is the same root cause, haven't had it happen after this fix).

And conceptually the `position=fixed` needs to be reset as well, I think, it's a way to force disabling the scrolling.

**Comment by 5chufti** [comment]
you can check it on https://www.heise.de/newsticker/

**Comment by NicolaeNMV** [comment]
@5chufti excellent, thanks for providing an example ! I've now added the functionality to remove position=fixed. Will release the new extension shortly.

**Comment by 5chufti** [comment]
Hi, I'm eagerly waiting for the new release as the a.m. website has changed to more agressive and one can't skip the overlay with hitting "ESC" any longer ...

**Pull request closed without merging**
